-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS portfolio_test (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  client_code varchar(20) NOT NULL,
  provider varchar(50) NOT NULL,
  total_active_deposits int NOT NULL,
  invested_value numeric(19, 4) NULL,
  current_value numeric(19, 4) NULL,
  interest_earned numeric(19, 4) NULL,
  returns_value numeric(19, 4) NULL,
  returns_percentage numeric(19, 4) NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(50) NOT NULL,
  updated_by varchar(50) NOT NULL,
  CONSTRAINT portfolio_test_pkey PRIMARY KEY (id),
  CONSTRAINT unique_client_provider_test UNIQUE (client_code, provider)
);
CREATE INDEX portfolio_test_created ON portfolio_test (created_at);
CREATE INDEX portfolio_test_updated ON portfolio_test (updated_at);
CREATE INDEX portfolio_test_clientcode ON portfolio_test (client_code);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE portfolio_test DROP CONSTRAINT portfolio_test_pkey;
ALTER TABLE portfolio_test DROP CONSTRAINT unique_client_provider_test;
DROP INDEX portfolio_test_created;
DROP INDEX portfolio_test_updated;
DROP INDEX portfolio_test_clientcode;
drop table portfolio_test;
-- +goose StatementEnd
