-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS wb_events_test (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  client_code varchar(20) NOT NULL,
  vendor varchar(50) NOT NULL,
  tracking_id varchar(100) NULL,
  event_type varchar(50) NULL,
  institution varchar(100) NULL,
  type varchar(50) NULL,
  amount numeric(19, 4) NULL,
  tenure_months numeric(2) NULL,
  tenure_days numeric(2) NULL,
  failure_reason varchar(200) NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(50) NOT NULL,
  updated_by varchar(50) NOT NULL,
  CONSTRAINT wb_events_test_pkey PRIMARY KEY (id)
);
CREATE INDEX wb_events_test_index_created ON wb_events_test (created_at);
CREATE INDEX wb_events_test_index_updated ON wb_events_test (updated_at);
CREATE INDEX wb_events_test_index_clientcode ON wb_events_test (client_code);
CREATE INDEX wb_events_test_index_eventtype ON wb_events_test (event_type);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE wb_events_test DROP CONSTRAINT wb_events_test_pkey;
DROP INDEX wb_events_test_index_created;
DROP INDEX wb_events_test_index_updated;
DROP INDEX wb_events_test_index_clientcode;
DROP INDEX wb_events_test_index_eventtype;
drop table wb_events_test;
-- +goose StatementEnd
