-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS portfolio (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  client_code varchar(20) NOT NULL,
  provider varchar(50) NOT NULL,
  total_active_deposits int NOT NULL,
  invested_value numeric(19, 4) NULL,
  current_value numeric(19, 4) NULL,
  interest_earned numeric(19, 4) NULL,
  returns_value numeric(19, 4) NULL,
  returns_percentage numeric(19, 4) NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(50) NOT NULL,
  updated_by varchar(50) NOT NULL,
  CONSTRAINT portfolio_pkey PRIMARY KEY (id),
  CONSTRAINT unique_client_provider UNIQUE (client_code, provider)
);
CREATE INDEX portfolio_created ON portfolio (created_at);
CREATE INDEX portfolio_updated ON portfolio (updated_at);
CREATE INDEX portfolio_clientcode ON portfolio (client_code);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE portfolio DROP CONSTRAINT portfolio_pkey;
ALTER TABLE portfolio DROP CONSTRAINT unique_client_provider;
DROP INDEX portfolio_created;
DROP INDEX portfolio_updated;
DROP INDEX portfolio_clientcode;
drop table portfolio;
-- +goose StatementEnd
