-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS webhook_events (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  client_code varchar(20) NOT NULL,
  vendor varchar(50) NOT NULL,
  tracking_id varchar(100) NULL,
  event_type varchar(50) NULL,
  institution varchar(100) NULL,
  type varchar(50) NULL,
  amount numeric(19, 4) NULL,
  tenure_months numeric(2) NULL,
  tenure_days numeric(2) NULL,
  failure_reason varchar(200) NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(50) NOT NULL,
  updated_by varchar(50) NOT NULL,
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id)
);
CREATE INDEX webhook_events_index_created ON webhook_events (created_at);
CREATE INDEX webhook_events_index_updated ON webhook_events (updated_at);
CREATE INDEX webhook_events_index_clientcode ON webhook_events (client_code);
CREATE INDEX webhook_events_index_eventtype ON webhook_events (event_type);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
ALTER TABLE webhook_events DROP CONSTRAINT webhook_events_pkey;
DROP INDEX webhook_events_index_created;
DROP INDEX webhook_events_index_updated;
DROP INDEX webhook_events_index_clientcode;
DROP INDEX webhook_events_index_eventtype;
drop table webhook_events;
-- +goose StatementEnd