-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS pending_journey_test (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	client_code varchar(20) NOT NULL,
	provider varchar(60) NOT NULL,
	pending bool NULL,
	payment_pending bool NULL,
	kyc_pending bool NULL,
	created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	created_by varchar(50) NULL,
	updated_by varchar(50) NULL,
	CONSTRAINT pending_journey_test_pkey PRIMARY KEY (id),
	CONSTRAINT unique_clientcode_provider_test UNIQUE (client_code, provider)
);
CREATE INDEX pending_journey_test_created ON pending_journey_test (created_at);
CREATE INDEX pending_journey_test_updated ON pending_journey_test (updated_at);
CREATE INDEX pending_journey_test_clientcode ON pending_journey_test (client_code);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE pending_journey_test DROP CONSTRAINT pending_journey_test_pkey;
ALTER TABLE pending_journey_test DROP CONSTRAINT unique_clientcode_provider_test;
DROP INDEX pending_journey_test_created;
DROP INDEX pending_journey_test_updated;
DROP INDEX pending_journey_test_clientcode;
drop table pending_journey_test;
-- +goose StatementEnd
